version: '3.8'

services:
  app:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    environment:
      - DEBUG=True

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
    depends_on:
      - mongo
    networks:
      - mongo-net

volumes:
  mongo-data:

networks:
  mongo-net:
    driver: bridge 